version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: okr_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: okr_db
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: okr_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  mysqldata:
  redisdata:
